version: "3.8"

services:
  # eureka-sv container
  eureka-sv:
    build: eureka-sv
    container_name: eureka-sv
    ports:
      - "8761:8761"
    restart: unless-stopped
    networks:
      - clinica_network


networks:
  clinica_network:
    external: true
