server:
  port: 443
  ssl:
    key-store: file:/app/keystore.p12
    key-store-password: Cracks06!teamganador
    key-store-type: PKCS12
    key-alias: gateway-ssl

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9090/realms/spring-boot-real-dev


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}