server:
  port: 443

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: keycloak
          uri: http://vps-4722960-x.dattaweb.com:9090
          predicates:
            - Path=/keycloak/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9090/realms/spring-boot-real-dev


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}