version: "@project.version@"

server:
  port: 8083

spring:
  application:
    name: medpatient-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${BD}
    username: ${USER_BD}
    password: ${PASSWORD_BD}
  #Keycloak Config
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/spring-boot-real-dev
          jwk-set-uri: http://localhost:9090/realms/spring-boot-real-dev/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}

jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: spring-client-api-rest-clinica