version: "@project.version@"

server:
  port: 8083

spring:
  application:
    name: medpatient-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${BD}
    username: ${USER_BD}
    password: ${PASSWORD_BD}

security:
  jwt:
    key: 18779077150cd4e1767d1390cf318d5067226af509a26ae311975e9f05c7cfe6
    user:
      generator: AUTHJWT-BACKEND

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}