spring:
  application:
    name: finance-service

  datasource:
    url: jdbc:mysql://localhost:3306/facturacion
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka