spring:
  application:
    name: finance-service

  datasource:
    url: ${BD}
    username: ${USER_BD}
    password: ${PASSWORD_BD}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}