spring:
  application:
    name: medical-service

  datasource:
    url: jdbc:mysql://${BD}
    username: ${USER_BD}
    password: ${PASSWORD_BD}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka