server:
  port: 8085

spring:
  application:
    name: auth-service

  #Database Config
  datasource:
    url: jdbc:mysql://${BD}
    username: ${USER_BD}
    password: ${PASSWORD_BD}


  #Keycloak Config
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/spring-boot-real-dev
          jwk-set-uri: http://localhost:9090/realms/spring-boot-real-dev/protocol/openid-connect/certs

logging:
  level:
    org:
      keycloack: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


      default-zone: http://localhost:8761/eureka

jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: spring-client-api-rest-clinica
