server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/NicolasMoralesDev/clinica_backend/tree/feature/config-server
          searchPaths: config-data